iss.settings:
  type: config_object
  label: 'ISS settings'
  mapping:
    api_key:
      type: string
      label: 'Api Key'
    api_endpoint:
      type: string
      label: 'Endpoint'
    regimen_fiscal:
      type: integer
      label: 'Régimen Fiscal'
    lugar_expedicion:
      type: integer
      label: 'Lugar de expedición'
    serie:
      type: string
      label: 'Serie'
    folio:
      type: string
      label: 'Folio'
    num_rows:
      type: string
    stamp_date:
      type: string
    c_pago:
      type: string
